name: newsfeed_multiple_imageview
description: Facebook type multiple news feed images view.
version: 1.0.0
homepage: https://github.com/EjazAmir/newsfeed_multiple_imageview.git

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  transparent_image: ^2.0.1
  flutter_image_slideshow: ^0.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
